FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install only production deps
RUN npm install --production

# Copy rest of the code
COPY . .

# Expose backend port
EXPOSE 5001

# Start server
CMD ["node", "src/server.js"]